FROM debian:wheezy
LABEL maintainer="Johannes Innerbichler"

# Install dependencies
RUN apt-get update
RUN apt-get install -y curl tar

# Download database
RUN mkdir /mainnet_db/
WORKDIR "/tmp/"
RUN curl -O http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz
RUN tar xzfv /tmp/IOTA.partners-mainnetdb.tar.gz -C /mainnet_db/
RUN rm /tmp/IOTA.partners-mainnetdb.tar.gz
WORKDIR "/mainnet_db/"

# Create volume
VOLUME /mainnet_db
