version: '3'

services:

  iri:
    container_name: iri_node
    image: iotaledger/iri:v1.4.1.4
    ports:
      - "14265:14265"
      - "14777:14777/udp"
      - "15777:15777"
    volumes:
      - ./config/iota.ini:/iri/iota.ini
      - ./config/logback.xml:/iri/conf/logback.xml
      - mainnet_db:/iri/mainnet_db
    restart: always
    depends_on:
      - database
    entrypoint:
      - "/usr/bin/java"
      - "-XX:+DisableAttachMechanism"
      - "-Xmx8g"
      - "-Xms256m"
      - "-Dlogback.configurationFile=/iri/conf/logback.xml"
      - "-Djava.net.preferIPv4Stack=true"
      - "-jar"
      - "iri.jar"
      - "--remote"

  database:
    container_name: iri_database
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - mainnet_db:/mainnet_db

  nelson:
    image: romansemko/nelson:latest
    container_name: iri_nelson
    ports:
      - "18600:18600"
      - "16600:16600"
    depends_on:
      - iri
    volumes:
      - ./config/nelson.ini:/iri/nelson.ini
    command: ["--config", "/iri/nelson.ini"]

  dashboard:
    container_name: iri_dashboard
    build:
      context: .
      dockerfile: Dockerfile-ipm
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /root/
    depends_on:
      - iri
    entrypoint:
       - iota-pm
       - "--iri=http://iri:14265"
       - "--port=0.0.0.0:80"
       - "--refresh=10"

  start_iri:
    image: dadarek/wait-for-dependencies
    depends_on:
      - iri
      - database
    command: iri:14265

volumes:
  mainnet_db: