version: '3'

services:
  iri:
    image: iotaledger/iri:v1.4.1.2
    container_name: iri_node
    ports:
      - "14265:14265"
      - "14777:14777/udp"
      - "15777:15777"
    volumes:
      - ./config/iota.ini:/iri/iota.ini
      - ./config/logback.xml:/iri/conf/logback.xml
      - ./mainnet_db:/iri/mainnet_db
    restart: always
    entrypoint:
      - "/usr/bin/java"
      - "-XX:+DisableAttachMechanism"
      - "-Xmx8g"
      - "-Xms256m"
      - "-Dlogback.configurationFile=/iri/conf/logback.xml"
      - "-Djava.net.preferIPv4Stack=true"
      - "-jar"
      - "iri.jar"
      - "--remote"
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile-ipm
    container_name: iri_dashboard
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /root/
    depends_on:
      - iri
    entrypoint:
       - iota-pm
       - "--iri=http://iri:14265"
       - "--port=0.0.0.0:80"
       - "--refresh=10"
